### ISSUE TITLE
be able to select multiple copies or notes for action of a task.

### ISSUE THREAD

**Issue by franco27** [clipto-pro/Desktop#20] opened 2019-10-01 15:37 UTC
Windows 10 x64 -  v1.3.0 

I would have liked to be able to select several notes at the same time to merge, delete,...
like in android version.

**Comment by atrashler** [comment] 2019-10-01 21:28
duplicate of #7

**Comment by franco27** [comment] 2019-10-01 21:40
Yes, indeed this suggestion is complementary to the other.

**Comment by atrashler** [comment] 2020-02-04 20:35
fixed in v2.1.0

**Closed by atrashler** 2020-02-04 20:35 UTC
Labels: duplicate
