### ISSUE TITLE
old notes exceeding the limit are not automatically deleted 

### ISSUE THREAD

**Issue by zzzop** [clipto-pro/Desktop#106] opened 2021-06-01 15:06 UTC
even if  copied new note, old notes exceeding the limit  are still there.
![微信截图_20210601225757](https://user-images.githubusercontent.com/28821632/120346037-98d56a80-c32d-11eb-85f5-fe332707c392.png)
![微信截图_20210601225724](https://user-images.githubusercontent.com/28821632/120346049-9b37c480-c32d-11eb-90a2-20011cb4f84d.png)

**Comment by klorinczi** [comment] 2021-06-02 06:40
Yes, I can confirm, the bug is still there.
Also it was already reported.

Duplicate of #90

**Comment by atrashler** [comment] 2021-06-02 07:50
> even if copied new note, old notes exceeding the limit are still there.
> ![微信截图_20210601225757](https://user-images.githubusercontent.com/28821632/120346037-98d56a80-c32d-11eb-85f5-fe332707c392.png)
> ![微信截图_20210601225724](https://user-images.githubusercontent.com/28821632/120346049-9b37c480-c32d-11eb-90a2-20011cb4f84d.png)

Could you provide additional info (to be sure that I finally found the issue):
1) do you have more than 1 device to sync your data between them (which platforms)?
2) do you work with the app offline while copying some data and sync your data later (or the internet is always available to the app)?
3) do you copy (or create) new data on only one device or different?

**Comment by atrashler** [comment] 2021-06-02 07:51
> Yes, I can confirm, the bug is still there.
> Also it was already reported.
> 
> Duplicate of #90

I have found some possible cause of the problem, but need to understand if it is the same issue...

**Comment by Senliast** [comment] 2021-06-19 14:30
Just would like to say that i also have the issue, its happening from time to time

**Comment by atrashler** [comment] 2021-06-19 14:53
> Just would like to say that i also have the issue, its happening from time to time

I know the reason how it could happen. Just need to implement “the cleaning logic”:-)

**Comment by atrashler** [comment] 2021-09-26 12:17
should be fixed in 7.2.0

**Closed as completed by atrashler** 2021-09-26 12:17 UTC
Labels: question, investigation
