### ISSUE TITLE
Untagged! Help!

### ISSUE THREAD

**Issue by Uformula** [clipto-pro/Desktop#124] opened 2021-10-25 22:10 UTC
Hi.  Great product.  But I have andriod, which says I have no untagged, which is how it should be, and I have both my Windows application and online saying that I have over 1000 untagged, which is NOT correct.  Pls help!

**Comment by atrashler** [comment] 2021-10-26 06:21
Could you please send me:

1) the versions of Android and Desktop apps
2) how did you delete 1000 untagged notes and on which platform (I suppose that you deleted 1000 notes before and expects it to be deleted from all platforms)
3) the screenshot of the left panel with tags, so I can understand how it looks on the problematic platform.

Thanks!

**Comment by Uformula** [comment] 2021-10-26 22:45
Hi thanks for the quick response:

   1. Android 7.1.14 -- Desktop 7.2.6
   2. I never deleted any notes.  The issue is that 1000+ notes are
   untagged on desktop and online versions, but not on Android device, which
   is the correct status.  I never did nor intended to untag 1000+ notes.
   It's pivotal these remain tagged the way I have them on my Android app.
   3. Pls see attached the Problematic pic (the Desktop version) and
   unproblematic (the android app)

Thanks very much for your help!

*Rodrigo C. Serrano *| Direct: 631 671 8584 | New York City, NY

**Comment by atrashler** [comment] 2021-10-27 07:21
No attachments:)
Btw, could you also send your account uid in Clipto? (Settings -> Astral Sync -> ID field)

**Comment by Uformula** [comment] 2021-10-27 23:13
That's weird.  Attaching again.

Account uid = tgaP2VCCBGNeG7sDjOpovXTh22t1

Thanks again!

*Rodrigo C. Serrano *| Direct: 631 671 8584 | New York City, NY

**Comment by Uformula** [comment] 2021-10-29 14:39
Hi.  Were you able to figure it out?  Thx again.

**Comment by atrashler** [comment] 2021-10-29 16:41
> Hi. Were you able to figure it out? Thx again. On Wed, Oct 27, 2021, 7:12 PM Rodrigo C. Serrano ***@***.***> wrote:
> […](#)

No attachments again:) Nevermind... 
Seems like the issue with the migration logic that should run when you open the latest versions of the app. But it did not work by some reasons... I will upgrade the migration script so the issue should be fixed with upcoming update of Android or Desktop app. Now, not action required from you. Just try to re-login one more time (if it will not help, the issue should be fixed with upcoming release, as I have told). Sorry for the inconvenience. I am updating the internal structure of how tags and files are stored, so it can be more useful. But it requires some change in the application logic and structure.

**Comment by Uformula** [comment] 2021-10-29 17:20
Hi thanks for getting back to me.

It seems that you mention the app is the issue.  But the way the tags are
classified in it are correct.

I never untagged 1000+ articles, which is what reflects in the desktop and
online versions.

Is it possible to override what's on there with what my app is registering,
which is the correct version?

Thx

**Comment by atrashler** [comment] 2021-10-29 17:32
> Hi thanks for getting back to me. It seems that you mention the app is the issue. But the way the tags are classified in it are correct. I never untagged 1000+ articles, which is what reflects in the desktop and online versions. Is it possible to override what's on there with what my app is registering, which is the correct version? Thx On Fri, Oct 29, 2021, 12:41 PM Alex Trashler ***@***.***> wrote:
> […](#)

The correct version should be with the tags (seems like on Android is the correct version).
Current problem is that the latest Desktop and Web versions can not see the old format, but the current Android version can. And by some reasons current Android version did not migrate old data to new format. If you create any new tag, it will be visible on all platforms and should be correctly linked with notes. But old tags will not and the migration should be done.. Do not worry, I will prepare a migration logic, so all your notes will be linked with the new metadata structure. It will not affect any other notes attributes, only tags.

**Comment by Uformula** [comment] 2021-10-29 17:50
Ok great.  When should I follow up with you on this?

**Comment by atrashler** [comment] 2021-10-29 21:07
> Ok great. When should I follow up with you on this? On Fri, Oct 29, 2021, 1:32 PM Alex Trashler ***@***.***> wrote:
> […](#)

Approximately the beginning of the next week. I will prepare some logic during the weekends, but will test on the next week. I will text you in this thread.

**Comment by Uformula** [comment] 2021-10-30 14:02
Ok will connect sun Nov 7 or Mon Nov 8th.  Thanks again for your attention!
Good weekend!

**Comment by atrashler** [comment] 2021-11-01 10:46
> Ok will connect sun Nov 7 or Mon Nov 8th. Thanks again for your attention! Good weekend! On Fri, Oct 29, 2021, 5:07 PM Alex Trashler ***@***.***> wrote:
> […](#)

In Beta channel on Google Play will be published new release (7.2.8 >). It contains logic which should help to upgrade the local and remote index. Please check it, once it will be available in Beta channel. Approximately the updated version will be published today.

**Comment by Uformula** [comment] 2021-11-01 11:45
Hi Alex thank you for letting me know.

Again, just to make sure, this sounds like instructions to load a program
onto my Android device, which isn't the platform that is showing the
incorrect information.

 It's online and the windows program that is showing the incorrect
information with all the untagged notes. Therefore, I would think that any
program to correct the untagged notes should be loaded via those platforms.
Am I wrong in thinking this? Why am I loading something onto my Android
device? How does this fix the problem on the windows and online platforms?
Thank you so much again for your time and attention

**Comment by atrashler** [comment] 2021-11-01 12:02
> Hi Alex thank you for letting me know. Again, just to make sure, this sounds like instructions to load a program onto my Android device, which isn't the platform that is showing the incorrect information. It's online and the windows program that is showing the incorrect information with all the untagged notes. Therefore, I would think that any program to correct the untagged notes should be loaded via those platforms. Am I wrong in thinking this? Why am I loading something onto my Android device? How does this fix the problem on the windows and online platforms? Thank you so much again for your time and attention
> […](#)

The problem is because of the next:
1) Starting from version 7.x the app uses new internal structure to store tags (and files) in the cloud and across devices.
2) To support new structure, I have prepared some 'migration logic' on both Android and Web/Desktop.
3) Because the prepared logic is supposed to work in backward compatibility mode (at the moment when the logic was created, the versions of Desktop and Mobile were difference), I have also implemented some logic which should make it happen.
4) ...But things got out of control... and mobile app started using the old structure and desktop the new one.
5) Now I upgraded the mobile app (7.2.8) to migrate all old data to the new structure
6) It means that after upgrade to the mobile version 7.2.8, it will fix all issues with tags, publish updates to the cloud and start using the new structure as it is done on Desktop.
7) Later the same behaviour will be ported on Desktop. So if someone does not use mobile app, the migration could still be possible.

The current problem is that the 'old tags structure' was not correctly migrated to the 'new tags structure'. Android see the old structure, but Desktop see the new..

Let me know once you update the app.

**Comment by Uformula** [comment] 2021-11-01 12:21
Thanks very much for your explanation. How do I access the beta channel on
Google Play app? Could you send me a link please?

**Comment by Uformula** [comment] 2021-11-01 12:22
Nevermind i found it thx

**Comment by Uformula** [comment] 2021-11-01 13:26
Ok installed.  Now out says on the android version that i have 51 untagged
notes.

**Comment by Uformula** [comment] 2021-11-01 13:28
Now it* says

**Comment by atrashler** [comment] 2021-11-01 15:37
If it has untagged notes (which must not be untagged), try to sign out and sign in again (the app will try to rebuild the index again).

**Comment by atrashler** [comment] 2021-11-01 15:40
> If it has untagged notes (which must not be untagged), try to sign out and sign in again (the app will try to rebuild the index again).

As I can see from the logs, your data was not fully updated. Try to sign out and sign in again.

**Comment by atrashler** [comment] 2021-11-01 15:44
If after sign in there were no changes, please do the following:
1) Go to Settings -> Astral Sync
2) Click on the item 'Rebuild data index'
3) Send me the result of its execution (a screenshot with the modal dialog) after the rebuild is finished

**Comment by atrashler** [comment] 2021-11-01 15:49
BTW, make sure that the app has an access to the internet and is not blocked by adblockers, firewalls.
The weird thing now it that the server logs do not contains any information about possible migration that should run automatically after you open the app... And please check the previous two scenarios.

**Comment by Uformula** [comment] 2021-11-01 15:57
Ok I signed back into the app and no more untagged But now many of it not
all have duplicate tags.  ie two of the same tag.

*Rodrigo C. Serrano *| Direct: 631 671 8584 | New York City, NY

**Comment by Uformula** [comment] 2021-11-01 16:01
Looking more into it.  Looks like it has identified the duplicate tag
separately.  So now instead of 5 tags, I have ten total tags (2 of the same
for each 5 original categories).

Am sending you a snapshot.  Hopefully it goes through.



*Rodrigo C. Serrano *| Direct: 631 671 8584 | New York City, NY

**Comment by atrashler** [comment] 2021-11-01 16:13
> Looking more into it. Looks like it has identified the duplicate tag separately. So now instead of 5 tags, I have ten total tags (2 of the same for each 5 original categories). Am sending you a snapshot. Hopefully it goes through. *Rodrigo C. Serrano *| Direct: 631 671 8584 | New York City, NY On Mon, Nov 1, 2021 at 11:56 AM Rodrigo C. Serrano ***@***.***> wrote:
> […](#)

Are you sure that the tags are duplicated? The names of the tags are sensitive to spaces, commas between characters, upper-lower case, etc.. Please send a part of the screenshot (not via Github, seems like it does not let you attach screenshots:) with any note which has two identical tag names.

**Comment by atrashler** [comment] 2021-11-01 16:20
If some tags seem like duplicated and you want to remove one of them from all your notes and at the same time assign the other tag to the same selected notes:

1) navigate to the tag you want to remove
2) select all notes in the list with the given tag 
3) in the context menu click on ':menu -> Common tags'
4) uncheck the selected tag and check any other you want to apply to the selected notes
5) confirm your action

After that, all selected notes will be marked with the newly assigned tags and any unchecked tags will be removed from the selected notes.

**Comment by Uformula** [comment] 2021-11-01 18:06
Ok I think I got it squared away.  Thanks for all your help!  Great
product!  Will touch base if anything related comes up.  Good day!

*Rodrigo C. Serrano *| Direct: 631 671 8584 | New York City, NY

**Comment by Uformula** [comment] 2021-11-01 18:06
Oh Last thing.  Is there a way to migrate the account to another email
address?

*Rodrigo C. Serrano *| Direct: 631 671 8584 | New York City, NY

**Comment by atrashler** [comment] 2021-11-15 20:57
Sorry for the delay. Have not seen this update.
To migrate the account (if your account does not have any files):
1) Settings -> Time Machine -> Export data to a file
2) Sign out
3) Sing in with the new account
4) Settings -> Time Machine -> Import data from a file

If few more users will ask the same question, I will write a script to do it automatically with all user's data:)

**Closed as completed by atrashler** 2021-11-15 20:57 UTC
